server:
  port: ${PORT:8080}

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/telegram_bot?serverTimezone=UTC"
    username: ${DB_NAME:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    hibernate.ddl-auto: create-drop
    show-sql: true
    properties.hibernate.format_sql: true

bot:
  name: ${TGBOT_NAME:MyBestPlaceBot}
  token: ${TGBOT_TOKEN:1573515309:AAHYQmbjkFk4pigKTQklchWhQCRJHNEYch4}

